import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./pico.css";
import "./globals.css";
import Header from "@/lib/components/Header/Header";
import Footer from "@/lib/components/Footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Anna Svensson - Lägenheter i Söderköping",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="sv" data-theme="light">
      <link rel="icon" href="/favicon.ico" />
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Header ownerName="Anna Svensson" />
        <main style={{ minHeight: "75vh" }}>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
