import type { Metadata } from 'next'
import { Inter, Playfair_Display, IBM_Plex_Mono } from 'next/font/google'
import './pico.css'
import './globals.css'
import 'leaflet/dist/leaflet.css'
import Header from '@/lib/components/Header/Header'
import Footer from '@/lib/components/Footer/Footer'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
})

const playfair = Playfair_Display({
  subsets: ['latin'],
  variable: '--font-playfair',
  display: 'swap',
})

const ibmMono = IBM_Plex_Mono({
  subsets: ['latin'],
  weight: ['600', '700'], // for black/bold
  variable: '--font-ibm-mono',
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Anna Svensson - Lägenheter i Söderköping',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="sv" data-theme="light">
      <link rel="icon" href="/favicon.ico" />
      <body className={`${inter.variable} ${playfair.variable} ${ibmMono.variable}`}>
        <Header ownerName="Anna Svensson" />
        <main style={{ minHeight: '75vh' }}>{children}</main>
        <Footer />
      </body>
    </html>
  )
}
